// Script:    teste_conteudo.script
// Autor:     Robert Correa
// Data:      03/out/2013
// Propósito: Testar completamente o módulo conteudo
//

== Declarar as condicoes de retorno

=declararparm   conteudo0	   int 0

=declararparm   OK             int  0
//*********************************

== Testar criação do Conteudo

=criarConteudo		conteudo0	"conteudo 1"	OK
=destruirConteudo	conteudo0					OK